[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

# Add these new settings
[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window]
decorations = "none"
opacity = 0.7           
startup_mode = "FullScreen"
blur = true

[window.padding]
x = 1
y = 1

[general]
live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
