[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

# [env]
# TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Maple Mono NF Bold"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF Bold Italic"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF Italic"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "f"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "c"
mods = "super"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
chars = "\u001b\u000d"

[scrolling]
history = 50000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window]
decorations = "none"
opacity = 0.8
# option_as_alt = "Both"
startup_mode = "FullScreen"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["C:/Users/Snehil Shah/AppData/Roaming/alacritty/alacrittycatppuccin-mocha.toml"]

[terminal.shell]
program='ubuntu2204.exe'
